Source/NET/Chargify.MVC4/Controllers/SignupController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Globalization;
using System.Linq;
using System.Web.Mvc;
using System.Web.Routing;
using System.Web.Security;
using Chargify.MVC4.Filters;
using Chargify.MVC4.Models;
using ChargifyNET;
using ChargifyNET.Configuration;
using WebMatrix.WebData;

namespace Chargify.MVC4.Controllers
{
    [InitializeSimpleMembership]
    public class SignupController : Controller
    {
        //
        // GET: /Signup/Local/product-handle

        public ActionResult Local(string id)
        {
            //LocalSignup model = new LocalSignup();
            //model.UserPayment = new BillingPaymentModel();

            // Create the next 10 years for the credit card expiration
            List<SelectListItem> expYears = new List<SelectListItem>();
            for (int i = 0; i <= 10; i++)
            {
                string year = (DateTime.Today.Year + i).ToString();
                expYears.Add(new SelectListItem { Text = year, Value = year });
            }
            ViewBag.ExpYears = new SelectList(expYears, "Value", "Text");

            IEnumerable<SelectListItem> expMonths = DateTimeFormatInfo.InvariantInfo.MonthNames.Where(m => !String.IsNullOrEmpty(m)).Select((monthName, index) => new SelectListItem
            {
                Value = (index + 1).ToString(),
                Text = (index + 1).ToString("00")
            });

            ViewBag.ExpMonths = new SelectList(expMonths, "Value", "Text");

            var product = Chargify.LoadProduct(id);
            ViewBag.ProductName = product.Name ?? string.Empty;

            return View();
        }

        //
        // POST: /Signup/Local/product-handle

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Local(LocalSignup model, string id)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    // Attempt to register the user
                    Guid userId = Guid.NewGuid();
                    var newUser = WebSecurity.CreateUserAndAccount(model.User.UserName, model.User.Password, new { Email = model.UserContact.EmailAddress, UserId = userId });

                    if (newUser != null)
                    {
                        if (!Roles.RoleExists("user"))
                        {
                            Roles.CreateRole("user");
                        }
                        Roles.AddUsersToRoles(new string[] { model.User.UserName }, new string[] { "User" });

                        // Now that the user is created, attempt to create the corresponding subscription
                        var customerInfo = new CustomerAttributes()
                        {
                            FirstName = model.UserContact.FirstName,
                            LastName = model.UserContact.LastName,
                            Email = model.UserContact.EmailAddress,
                            SystemID = userId.ToString()
                        };

                        var paymentAttributes = new CreditCardAttributes()
                        {
                            FullNumber = model.UserPayment.CardNumber.Trim(),
                            CVV = model.UserPayment.CVV,
                            ExpirationMonth = model.UserPayment.ExpirationMonth,
                            ExpirationYear = model.UserPayment.ExpirationYear,
                            BillingAddress = model.UserAddress.Address,
                            BillingCity = model.UserAddress.City,
                            BillingZip = model.UserAddress.Zip,
                            BillingState = model.UserAddress.State,
                            BillingCountry = model.UserAddress.Country
                        };
                        

                        try
                        {
                            var newSubscription = Chargify.CreateSubscription(id, customerInfo, paymentAttributes);

                            WebSecurity.Login(model.User.UserName, model.User.Password, false);
                            return RedirectToAction("Index", "Site");
                        }
                        catch (ChargifyException ex)
                        {
                            if (ex.ErrorMessages.Count > 0)
                            {
                                ModelState.AddModelError("", ex.ErrorMessages.FirstOrDefault().Message);
                            }
                            else
                            {
                                ModelState.AddModelError("", ex.ToString());
                            }
                        }
                    }
                    else
                    {
                        //ModelState.AddModelError("", AccountValidation.ErrorCodeToString(createStatus));
                    }
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Completed()
        {
            return View();
        }

        public JsonResult ValidateCoupon(string couponCode)
        {
            
            return Json(null);
        }

        #region Helpers
        private ChargifyConnect Chargify
        {
            get
            {
                if (HttpContext.Cache["Chargify"] == null)
                {
                    ChargifyAccountRetrieverSection config = ConfigurationManager.GetSection("chargify") as ChargifyAccountRetrieverSection;
                    ChargifyAccountElement accountInfo = config.GetDefaultOrFirst();
                    ChargifyConnect chargify = new ChargifyConnect();
                    chargify.apiKey = accountInfo.ApiKey;
                    chargify.Password = accountInfo.ApiPassword;
                    chargify.URL = accountInfo.Site;
                    chargify.SharedKey = accountInfo.SharedKey;
                    chargify.UseJSON = config.UseJSON;

                    HttpContext.Cache.Add("Chargify", chargify, null, System.Web.Caching.Cache.NoAbsoluteExpiration, System.Web.Caching.Cache.NoSlidingExpiration, System.Web.Caching.CacheItemPriority.High, null);
                }

                return HttpContext.Cache["Chargify"] as ChargifyConnect;
            }
        }
        #endregion
    }
}

Source/NET/Chargify.MVC4/Views/Signup/Completed.cshtml
@{
    ViewBag.Title = "Completed";
}

<h2>Completed</h2>

Source/NET/Chargify.MVC4/Views/Signup/Local.cshtml
@model Chargify.MVC4.Models.LocalSignup

@{
    ViewBag.Title = "Local Signup";
}

<div class="row">
    <div class="span3">
        <h2>Local Signup</h2>
        <h3>@ViewBag.ProductName</h3>
        <p>On this page, the user is required to complete the form which allows the system to both create a user, and create a corresponding customer in the associated Chargify account.</p>
        <p>When the user clicks on the 'Place My Order' button, the system will create an ASP.NET membership user first, then create the Chargify customer second.</p>
        <p><i>You can simulate a non-working credit card by using '2' as the number instead of the default '1' ...</i></p>
    </div>
    <div class="span9" style="margin-top: 20px;">
        <p class="alert alert-info">Please enter the following information and click 'Place My Order' to complete the signup process.</p>
        @using (Html.BeginForm("Local", "Signup", FormMethod.Post, new { @class = "form-horizontal" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)

            <fieldset>
                <legend>Billing Information</legend>

                <div class="control-group">
                    @Html.LabelFor(model => model.UserPayment.CardNumber, new { @class = "control-label" })
                    <div class="controls">
                        @Html.EditorFor(model => model.UserPayment.CardNumber)
                        @Html.ValidationMessageFor(model => model.UserPayment.CardNumber)
                    </div>
                </div>

                <div class="control-group">
                    <label class="control-label" for="ExpMonth">Expiry</label>
                    <div class="controls">
                        @Html.DropDownListFor(model => model.UserPayment.ExpirationMonth, (SelectList)ViewBag.ExpMonths, "Month", new { @class = "input-small" }) /
                                @Html.DropDownListFor(model => model.UserPayment.ExpirationYear, (SelectList)ViewBag.ExpYears, "Year", new { @class = "input-small" })
                        @Html.ValidationMessageFor(model => model.UserPayment.ExpirationMonth)
                        @Html.ValidationMessageFor(model => model.UserPayment.ExpirationYear)
                    </div>
                </div>

                <div class="control-group">
                    @Html.LabelFor(model => model.UserPayment.CVV, new { @class = "control-label" })
                    <div class="controls">
                        @Html.EditorFor(model => model.UserPayment.CVV)
                        @Html.ValidationMessageFor(model => model.UserPayment.CVV)
                    </div>
                </div>

                <div class="control-group">
                    @Html.LabelFor(model => model.UserAddress.Address, new { @class = "control-label" })
                    <div class="controls">
                        @Html.EditorFor(model => model.UserAddress.Address)
                    </div>
                </div>

                <div class="control-group">
                    @Html.LabelFor(model => model.UserAddress.Country, new { @class = "control-label" })
                    <div class="controls">
                        @Html.EditorFor(model => model.UserAddress.Country)
                    </div>
                </div>

                <div class="control-group">
                    @Html.LabelFor(model => model.UserAddress.State, new { @class = "control-label" })
                    <div class="controls">
                        @Html.EditorFor(model => model.UserAddress.State)
                    </div>
                </div>

                <div class="control-group">
                    @Html.LabelFor(model => model.UserAddress.City, new { @class = "control-label" })
                    <div class="controls">
                        @Html.EditorFor(model => model.UserAddress.City)
                    </div>
                </div>

                <div class="control-group">
                    @Html.LabelFor(model => model.UserAddress.Zip, new { @class = "control-label" })
                    <div class="controls">
                        @Html.EditorFor(model => model.UserAddress.Zip)
                    </div>
                </div>

                <div class="control-group">
                    @Html.LabelFor(model => model.CouponCode, new { @class = "control-label" })
                    <div class="controls">
                        <div class="input-append">
                            @Html.EditorFor(model => model.CouponCode)
                            <button class="btn" type="button">Validate</button>
                        </div>
                    </div>
                </div>

            </fieldset>
    
            <fieldset>
                <legend>Contact Information</legend>

                <div class="control-group">
                    @Html.LabelFor(model => model.UserContact.EmailAddress, new { @class = "control-label" })
                    <div class="controls">
                        @Html.EditorFor(model => model.UserContact.EmailAddress)
                    </div>
                </div>

                <div class="control-group">
                    @Html.LabelFor(model => model.UserContact.FirstName, new { @class = "control-label" })
                    <div class="controls">
                        @Html.EditorFor(model => model.UserContact.FirstName)
                    </div>
                </div>

                <div class="control-group">
                    @Html.LabelFor(model => model.UserContact.LastName, new { @class = "control-label" })
                    <div class="controls">
                        @Html.EditorFor(model => model.UserContact.LastName)
                    </div>
                </div>

            </fieldset>
            
            <fieldset>
                <legend>Account Information</legend>

                <div class="control-group">
                    @Html.LabelFor(model => model.User.UserName, new { @class = "control-label" })
                    <div class="controls">
                        @Html.EditorFor(model => model.User.UserName)
                    </div>
                </div>

                <div class="control-group">
                    @Html.LabelFor(model => model.User.Password, new { @class = "control-label" })
                    <div class="controls">
                        @Html.EditorFor(model => model.User.Password)
                    </div>
                </div>

                <div class="control-group">
                    @Html.LabelFor(model => model.User.ConfirmPassword, new { @class = "control-label" })
                    <div class="controls">
                        @Html.EditorFor(model => model.User.ConfirmPassword)
                    </div>
                </div>
            </fieldset>
           
            
            <div class="form-actions">
                <input class="btn btn-primary" type="submit" value="Place My Order" />
            </div>
    
        }
    </div>
</div>


<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $(document).ready(function () {
            //Update that validator
            $.validator.setDefaults({
                highlight: function (element) {
                    $(element).closest(".control-group").addClass("error");
                },
                unhighlight: function (element) {
                    $(element).closest(".control-group").removeClass("error");
                }
            });
        });
    </script>
}

Source/NET/Chargify.MVC4/Views/Signup/_PaymentInfo.cshtml
@model Chargify.MVC4.Models.BillingPaymentModel

<div class="control-group">
    @Html.LabelFor(model => model.CardNumber, new { @class = "control-label" })
    <div class="controls">
        @Html.EditorFor(model => model.CardNumber)
        @Html.ValidationMessageFor(model => model.CardNumber)
    </div>
</div>

<div class="control-group">
    <label class="control-label" for="ExpMonth">Expiry</label>
    <div class="controls">
        @Html.DropDownListFor(model => model.ExpirationMonth, (SelectList)ViewBag.ExpMonths, "Month", new { @class = "input-small" }) /
                @Html.DropDownListFor(model => model.ExpirationYear, (SelectList)ViewBag.ExpYears, "Year", new { @class = "input-small" })
        @Html.ValidationMessageFor(model => model.ExpirationMonth)
        @Html.ValidationMessageFor(model => model.ExpirationYear)
    </div>
</div>

<div class="control-group">
    @Html.LabelFor(model => model.CVV, new { @class = "control-label" })
    <div class="controls">
        @Html.EditorFor(model => model.CVV)
        @Html.ValidationMessageFor(model => model.CVV)
    </div>
</div>